### ISSUE TITLE
demo , return q[-1] list index out of range - error

### ISSUE THREAD

**Issue by En-J-A** [salesforce/simpletod#17]
When I try to run the demo by

`python demo.py gpt2 greedy`

I got this output with the following error

```
(venv) D:\simpletod-master\simpletod-master>python demo.py gpt2 greedy

Loading Model

SimpleTOD is ready to chat. What would you like to ask?

You: hello, I need a cheap hotel

Traceback (most recent call last):
  File "D:\simpletod-master\simpletod-master\demo.py", line 696, in <module>
    domain = get_turn_domain(beliefs, domain_queue)
  File "D:\simpletod-master\simpletod-master\demo.py", line 587, in get_turn_domain
    return q[-1]
IndexError: list index out of range
```
when I tried to print the output line by line 

I found that the belief_text and beliefs are empty :

 ```
   belief_text = get_belief_new_dbsearch(tmp_pred)
        print(belief_text)

        beliefs = convert_belief(belief_text)
        print(beliefs)

```
their values are:
```
 []
{}
```
Is there a problem with arguments?

**Comment by wise-east** [comment]
I have the same problem. Were you able to resolve this?

**Comment by En-J-A** [comment]
Unfortunately, no.

**Comment by mohiitaa** [comment]
Did you find a solution to this?
