### ISSUE TITLE
can't get the result reported in paper when using end2end training without dbsearch

### ISSUE THREAD

**Issue by fasterbuild** [salesforce/simpletod#7]
Hi all,
    with default parameters, I run end2end training without desearch, train file is resources/gpt2/train.history_belief_action_sys_delex with 56778 samples in the file. The ppl in valid set stop decreasing after only 2 epoch, got final valid set ppl=2.30. The success rate of test set is around 18.5%, much lower than 70.5% reported in paper table 3. And the belief acc is around 42%, also much lower than 55% in paper table 1. I wonder if the model is trained well with default params, would you please release your hyper parameters for end2end training and traing details?

**Comment by gungui98** [comment]
Hi @fasterbuild , I have the same problem as you and I don't even get the same accuracy as you did! could you share the hyper-params you are using?

**Comment by A-Fuad** [comment]
Please let me know how did you repeat the experiment because I could not do that and

 I use this line to execute main.py because I could not run the .sh files

```
python main.py  --train_data_file ./resources/gpt2/train.history_belief --output_dir ./outp
ut --model_type gpt2
```

thus, I got this error
```
WARNING:__main__:Process rank: -1, device: cuda, n_gpu: 1, distributed training: False, 16-bits training: False
Traceback (most recent call last):
  File "D:\simpletod-master\simpletod-master\main.py", line 415, in <module>
    main()
  File "D:\simpletod-master\simpletod-master\main.py", line 369, in main
    model, tokenizer, model_class, args = get_model_tokenizer(args)
  File "D:\simpletod-master\simpletod-master\main.py", line 75, in get_model_tokenizer
    raise ValueError(
ValueError: You are instantiating a new GPT2Tokenizer tokenizer. This is not supported, but you can do it from another script, save it,and load it from here
, using --tokenizer_name
```


Help me, please! @fasterbuild , @gungui98
